app = "mayu-live/starter"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[metrics]
  path = "/metrics"
  port = 9092

[[services]]
  http_checks = []
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  tcp_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls"]
    port = 443
    [services.ports.tls_options]
      alpn = ["h2"]

  [[services.script_checks]]
    command = "/fly/healthcheck.sh"
    interval = 10000
    restart_limit = 3
    timeout = 1000
